### ISSUE TITLE
Implement a calculation of the error compared to the true velocity

### ISSUE THREAD

**Issue by jenswaage** [EiT-Computer-Vision/velocity-estimation#16]
The true velocity can be retrieved from frame metadata, so functionality to retrieve this must be implemented. The functionality to calculate should be in the `data_processing` module. Then calculate the error by using a error measure, e.g. [mean squared error](https://en.wikipedia.org/wiki/Mean_squared_error). We should keep track of both the error for the current frames and the total error.

**Comment by TMasoud** [comment]
implemented!
added function get_error (absolute value)
added function to read metadata
